---
- name: Deploy kernel modules config
  ansible.builtin.template:
    src: ansible.conf.jinja2
    dest: /etc/modprobe.d/ansible.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root
